#!/bin/bash

set -e

#!/bin/bash

ham4db-client -c enable-semi-sync-master -i 127.0.0.1:10111

ham4db-client -c enable-semi-sync-replica -i 127.0.0.1:10112
sleep 2

ham4db-client -c disable-semi-sync-replica -i 127.0.0.1:10112
sleep 2
