
-- topology:
--
-- 22293
-- + 22294
--   + 22295
-- + 22296
-- + 22297
--
DELETE FROM ham_database_instance_maintenance;
DELETE FROM ham_database_instance_downtime;
DELETE FROM ham_database_instance;
DELETE FROM mysql_database_instance;
DELETE FROM ham_database_instance_tag;
DELETE FROM ham_database_instance_candidate;
DELETE FROM mysql_database_instance_stale_binlog_coordinate;

INSERT INTO ham_database_instance (uptime,hostname,port,cluster_id,cluster_name,cluster_alias,db_type,db_id,db_version,db_alias,db_state,db_role,pl_region,pl_data_center,pl_zone,last_attempted_check_timestamp,last_checked_timestamp,last_seen_timestamp,is_last_check_partial_success,upstream_host,upstream_port,downstream_hosts,downstream_count,replication_state,replication_depth,replication_downstream_lag,is_co_master,is_read_only,is_allow_tls,is_replication_credentials_available,has_replication_filters,has_replication_credentials) VALUES (670447,'testhost',22293,'xxxx-yyyy-uuuu-xxxx-yyyy-zzzzz','mysql-test','','mysql',1,'5.6','','','master','us-region','ny','','2017-02-02 08:29:57','2017-02-02 08:29:57','2017-02-02 08:29:57',0,'',0,'[{\"Hostname\":\"testhost\",\"Port\":22294},{\"Hostname\":\"testhost\",\"Port\":22297},{\"Hostname\":\"testhost\",\"Port\":22296}]',3,'',0,NULL,0,0,0,0,0,0);
INSERT INTO ham_database_instance (uptime,hostname,port,cluster_id,cluster_name,cluster_alias,db_type,db_id,db_version,db_alias,db_state,db_role,pl_region,pl_data_center,pl_zone,last_attempted_check_timestamp,last_checked_timestamp,last_seen_timestamp,is_last_check_partial_success,upstream_host,upstream_port,downstream_hosts,downstream_count,replication_state,replication_depth,replication_downstream_lag,is_co_master,is_read_only,is_allow_tls,is_replication_credentials_available,has_replication_filters,has_replication_credentials) VALUES (72466,'testhost',22294,'xxxx-yyyy-uuuu-xxxx-yyyy-zzzzz','mysql-test','','mysql',101,'5.6','','','','us-region','ny','','2017-02-02 08:29:57','2017-02-02 08:29:57','2017-02-02 08:29:57',0,'testhost',22293,'[{\"Hostname\":\"testhost\",\"Port\":22295}]',1,'',1,NULL,0,0,0,0,0,1);
INSERT INTO ham_database_instance (uptime,hostname,port,cluster_id,cluster_name,cluster_alias,db_type,db_id,db_version,db_alias,db_state,db_role,pl_region,pl_data_center,pl_zone,last_attempted_check_timestamp,last_checked_timestamp,last_seen_timestamp,is_last_check_partial_success,upstream_host,upstream_port,downstream_hosts,downstream_count,replication_state,replication_depth,replication_downstream_lag,is_co_master,is_read_only,is_allow_tls,is_replication_credentials_available,has_replication_filters,has_replication_credentials) VALUES (670442,'testhost',22295,'xxxx-yyyy-uuuu-xxxx-yyyy-zzzzz','mysql-test','','mysql',102,'5.6','','','','us-region','ny','','2017-02-02 08:29:57','2017-02-02 08:29:57','2017-02-02 08:29:57',0,'testhost',22294,'[]',0,'',2,NULL,0,0,0,0,0,1);
INSERT INTO ham_database_instance (uptime,hostname,port,cluster_id,cluster_name,cluster_alias,db_type,db_id,db_version,db_alias,db_state,db_role,pl_region,pl_data_center,pl_zone,last_attempted_check_timestamp,last_checked_timestamp,last_seen_timestamp,is_last_check_partial_success,upstream_host,upstream_port,downstream_hosts,downstream_count,replication_state,replication_depth,replication_downstream_lag,is_co_master,is_read_only,is_allow_tls,is_replication_credentials_available,has_replication_filters,has_replication_credentials) VALUES (670438,'testhost',22296,'xxxx-yyyy-uuuu-xxxx-yyyy-zzzzz','mysql-test','','mysql',103,'5.6','','','','us-region','ny','','2017-02-02 08:29:57','2017-02-02 08:29:57','2017-02-02 08:29:57',0,'testhost',22293,'[]',0,'',1,NULL,0,0,0,0,0,1);
INSERT INTO ham_database_instance (uptime,hostname,port,cluster_id,cluster_name,cluster_alias,db_type,db_id,db_version,db_alias,db_state,db_role,pl_region,pl_data_center,pl_zone,last_attempted_check_timestamp,last_checked_timestamp,last_seen_timestamp,is_last_check_partial_success,upstream_host,upstream_port,downstream_hosts,downstream_count,replication_state,replication_depth,replication_downstream_lag,is_co_master,is_read_only,is_allow_tls,is_replication_credentials_available,has_replication_filters,has_replication_credentials) VALUES (670435,'testhost',22297,'xxxx-yyyy-uuuu-xxxx-yyyy-zzzzz','mysql-test','','mysql',104,'5.6','','','','seattle','ny','','2017-02-02 08:29:57','2017-02-02 08:29:57','2017-02-02 08:29:57',0,'testhost',22293,'[]',0,'',1,NULL,0,0,0,0,0,1);

INSERT INTO mysql_database_instance (di_hostname, di_port, server_uuid, is_binlog_server, binlog_format, log_bin, log_slave_updates, binary_log_file, binary_log_pos, slave_sql_running, slave_io_running, oracle_gtid, master_uuid, ancestry_uuid, executed_gtid_set, gtid_purged, gtid_errant, supports_oracle_gtid, mariadb_gtid, pseudo_gtid, master_log_file, read_master_log_pos, relay_master_log_file, exec_master_log_pos, relay_log_file, relay_log_pos, last_sql_error, last_io_error, seconds_behind_master, sql_delay, semi_sync_enforced, version_comment, version_major, binlog_row_image, last_discovery_latency, semi_sync_master_enabled, semi_sync_replica_enabled, gtid_mode, replication_group_members) VALUES ('testhost',22293,'abcde-1',0,'STATEMENT',1,1,'mysql-bin.000167',137086726,0,0,0,'','','','','',0,0,1,'',0,'',0,'',0,'','',NULL,0,0,'MySQL Community Server (GPL)','5.6','full',0,0,0,'OFF', '[]');
INSERT INTO mysql_database_instance (di_hostname, di_port, server_uuid, is_binlog_server, binlog_format, log_bin, log_slave_updates, binary_log_file, binary_log_pos, slave_sql_running, slave_io_running, oracle_gtid, master_uuid, ancestry_uuid, executed_gtid_set, gtid_purged, gtid_errant, supports_oracle_gtid, mariadb_gtid, pseudo_gtid, master_log_file, read_master_log_pos, relay_master_log_file, exec_master_log_pos, relay_log_file, relay_log_pos, last_sql_error, last_io_error, seconds_behind_master, sql_delay, semi_sync_enforced, version_comment, version_major, binlog_row_image, last_discovery_latency, semi_sync_master_enabled, semi_sync_replica_enabled, gtid_mode, replication_group_members) VALUES ('testhost',22294,'abcde-2',0,'STATEMENT',1,1,'mysql-bin.000132',15931747,1,1,0,'','','','','',0,0,1,'mysql-bin.000167',137086726,'mysql-bin.000167',137086726,'mysql-relay.000029',15978254,'\"\"','\"\"',0,0,1,'MySQL Community Server (GPL)','5.6','full',0,0,0,'OFF', '[]');
INSERT INTO mysql_database_instance (di_hostname, di_port, server_uuid, is_binlog_server, binlog_format, log_bin, log_slave_updates, binary_log_file, binary_log_pos, slave_sql_running, slave_io_running, oracle_gtid, master_uuid, ancestry_uuid, executed_gtid_set, gtid_purged, gtid_errant, supports_oracle_gtid, mariadb_gtid, pseudo_gtid, master_log_file, read_master_log_pos, relay_master_log_file, exec_master_log_pos, relay_log_file, relay_log_pos, last_sql_error, last_io_error, seconds_behind_master, sql_delay, semi_sync_enforced, version_comment, version_major, binlog_row_image, last_discovery_latency, semi_sync_master_enabled, semi_sync_replica_enabled, gtid_mode, replication_group_members) VALUES ('testhost',22295,'abcde-3',0,'STATEMENT',1,1,'mysql-bin.000129',136688950,1,1,0,'','','','','',0,0,1,'mysql-bin.000132',15931747,'mysql-bin.000132',15931747,'mysql-relay.000002',15868528,'\"\"','\"\"',0,0,1,'MySQL Community Server (GPL)','5.6','full',0,0,0,'OFF', '[]');
INSERT INTO mysql_database_instance (di_hostname, di_port, server_uuid, is_binlog_server, binlog_format, log_bin, log_slave_updates, binary_log_file, binary_log_pos, slave_sql_running, slave_io_running, oracle_gtid, master_uuid, ancestry_uuid, executed_gtid_set, gtid_purged, gtid_errant, supports_oracle_gtid, mariadb_gtid, pseudo_gtid, master_log_file, read_master_log_pos, relay_master_log_file, exec_master_log_pos, relay_log_file, relay_log_pos, last_sql_error, last_io_error, seconds_behind_master, sql_delay, semi_sync_enforced, version_comment, version_major, binlog_row_image, last_discovery_latency, semi_sync_master_enabled, semi_sync_replica_enabled, gtid_mode, replication_group_members) VALUES ('testhost',22296,'abcde-4',0,'STATEMENT',0,1,'',0,1,1,0,'','','','','',0,0,1,'mysql-bin.000167',137086726,'mysql-bin.000167',137086726,'mysql-relay.000052',137086889,'\"\"','\"\"',0,0,1,'MySQL Community Server (GPL)','5.6','full',0,0,0,'OFF', '[]');
INSERT INTO mysql_database_instance (di_hostname, di_port, server_uuid, is_binlog_server, binlog_format, log_bin, log_slave_updates, binary_log_file, binary_log_pos, slave_sql_running, slave_io_running, oracle_gtid, master_uuid, ancestry_uuid, executed_gtid_set, gtid_purged, gtid_errant, supports_oracle_gtid, mariadb_gtid, pseudo_gtid, master_log_file, read_master_log_pos, relay_master_log_file, exec_master_log_pos, relay_log_file, relay_log_pos, last_sql_error, last_io_error, seconds_behind_master, sql_delay, semi_sync_enforced, version_comment, version_major, binlog_row_image, last_discovery_latency, semi_sync_master_enabled, semi_sync_replica_enabled, gtid_mode, replication_group_members) VALUES ('testhost',22297,'abcde-5',0,'STATEMENT',1,1,'mysql-bin.001013',106518535,1,1,0,'','','','','',0,0,1,'mysql-bin.000167',137086726,'mysql-bin.000167',137086726,'mysql-relay.000041',86111934,'\"\"','\"\"',0,0,1,'MySQL Community Server (GPL)','5.6','full',0,0,0,'OFF', '[]');

UPDATE mysql_database_instance SET replication_sql_thread_state=1 WHERE slave_sql_running=1;
UPDATE mysql_database_instance SET replication_io_thread_state=1  WHERE slave_io_running=1;
UPDATE mysql_database_instance SET replication_sql_thread_state=-1, replication_io_thread_state=-1 WHERE di_port=22293;

