FROM golang:1.14.4-stretch
LABEL maintainer="openark@github.com"

RUN apt-get update -q -y
RUN apt-get install -y sudo lsb-release rsync libaio1 numactl sqlite3 git jq less vim python bsdmainutils

COPY docker/resources/systemctl.py /usr/bin/systemctl

RUN mkdir /ham4db
WORKDIR /ham4db

WORKDIR /ham4db
COPY . .
RUN (cd /ham4db && script/build)

CMD (cd /ham4db && docker/docker-entry-raft && /bin/bash)
