#!/bin/bash
echo "# refreshing connections"
result=0
ham4db-client -c all-instances | while read i ; do
  test-retry ham4db-client -c flush-binary-logs -i $i > /dev/null 2>&1 || result=1
done
exit $result
